project:
  type: website
  preview:
    port: 4400

website:
  title: "3d-Printed Microsopes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
        - text: Labs Overview
          href: labs/
        - text: "Lab 1: Hello World"
          href: labs/lab1/
        - text: "Lab 2: Intro to Ray Tracing"
          href: labs/lab2/
        - text: "Lab 3: 3d-printed Microscope"
          href: labs/lab3/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true



